### PR TITLE
Detailed routeId instructions

### PR DESCRIPTION
**Pull request by radokristof**
I have made little improvements to the README. Now it might be easier for people to find the routeId for their favorite route.

### CODE REVIEW

**Comment by zttk** [comment]
I think there is an easier way. Just hover over the selected stop on the selected route on the left, and the link will have the route ID and stopID as well. Printscreen here:
http://www.tomkat.hu/MM/futar.jpg

Please see last line at the bottom, where Chrome displays the link when you hover the mouse over a stop.

**Comment by radokristof** [comment]
Thanks @zttk that works!

I will change to this method, this is really easier...

**Comment by balassy** [comment]
@radokristof Are you planning to update this PR?

**Comment by radokristof** [comment]
Yes, give me 5 minutes and I'll update it with @zttk instructions. Much easier method...

**Comment by balassy** [comment]
No need to hurry :)
Thank you very much!

**Comment by radokristof** [comment]
I have added a new commit, simplified the instructions a little bit.
If you find everything correct, now it is ready for merging :)

**Comment by balassy** [comment]
Excellent! Thank you very much for the contribution, I'm happy to merge it.

**Comment by balassy** [comment]
Released with version `1.2.0`: https://github.com/balassy/MMM-Futar/releases/tag/1.2.0

**Pull request merged**
